<a href="https://colab.research.google.com/github/bharatbudhori/ANN-and-CNN/blob/master/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Artificial Neural Network**

##Importing Libraries

In [32]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [33]:
tf.__version__

'2.6.0'

##Part 1 - Data Preprocessing

###Importing Datasets

In [34]:
dataset = pd.read_csv('Churn_Modelling.csv')
##features matrix
x = dataset.iloc[ : , 3:-1].values
##dependent variable vector
y = dataset.iloc[ : ,-1].values

In [35]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [36]:
print(y)

[1 0 1 ... 1 1 0]


###Encoding categorical data

Label Encoding the "Gender" column

In [37]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[ : , 2]=le.fit_transform(x[ : , 2])

In [38]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])] , remainder= 'passthrough')
x = np.array(ct.fit_transform(x))

In [40]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


###Splitting the dataset into the Training set and Test set

In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

###Feature Scaling

In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

##Part 2 - Building the ANN

###Initializing the ANN

In [43]:
ann = tf.keras.models.Sequential()

###Adding the input layer and first hidden layer

In [44]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

###Adding the second hidden layer

In [45]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

###Adding the Output layer

In [46]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

##Part 3 - Training the ANN

###Compiling the ANN

In [47]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

###Training the ANN on training set

In [48]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5616 - accuracy: 0.7501
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4688 - accuracy: 0.8049
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4450 - accuracy: 0.8099
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4337 - accuracy: 0.8163
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4267 - accuracy: 0.8180
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4207 - accuracy: 0.8196
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4148 - accuracy: 0.8209
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4095 - accuracy: 0.8236
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4047 - accuracy: 0.8265
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4005 - accura